title: Project

sections:
  information:
    headline: Πληροφορίες
    type: fields
    fields:
      featured_photo:
        label: Φωτογραφία
        help: Η φωτογραφία που θα φαίνεται στην εξωτερική σελίδα
        type: files
        max: 1
        layout: cards
        size: medium
        required: true
        width: 1/3

      intro:
        label: Εισαγωγικό κείμενο
        type: textarea
        size: medium
        buttons: false
        width: 2/3

      location:
        label: Τοποθεσία
        type: text
        width: 1/3

      date:
        label: Ημερομηνία ολοκλήρωσης έργου
        type: text
        width: 1/3

      category:
        label: Είδος
        type: tags
        options: query
        query: page.parent.children.pluck("category", ",", true)
        width: 1/3

  content:
    type: fields
    fields:
      main_content:
        label: Περιεχόμενο
        type: blocks
        fieldsets:
          image:
            extends: blocks/image
            fields:
              width:
                label: Image width
                type: select
                options:
                  full: Full width
                  normal: Normal
                  small: Small
                default: normal
          - text
          - gallery
